Repository brianfiszman/GoHexagonalBoilerplate, pull requests merged in 2021-08, with the labels that each got.

#6 [#1] Create .gitignore
  .gitignore
Labels: enhancement

#7 [#2] Create docker-compose.yml
  docker-compose.yml
Labels: enhancement

#10 Feature/#3 get list endpoint
  .env
  go.mod
  go.sum
  pkg/config/dotenv.config.go
  pkg/config/servicenow.config.go
  pkg/controllers/servicenow.controller.go
  pkg/main.go
  pkg/routers/servicenow.router.go
Labels: enhancement

#11 Feature/#5 create servicenow ticket
  .gitignore
  pkg/controllers/servicenow.controller.go
  pkg/routers/servicenow.router.go
Labels: enhancement

#16 [#4] Create getUsers endpoint
  pkg/controllers/servicenow.controller.go
  pkg/routers/servicenow.router.go
Labels: enhancement

#18 Bugfix/#17 rest conflict with service now
  .env
  .gitignore
  pkg/controllers/servicenow.controller.go
Labels: bug

#26 Feature/#19 create readme
  README.md
  pkg/containers/README.md
  pkg/controllers/README.md
  pkg/dtos/README.md
  pkg/models/repositories/README.md
  pkg/models/schemas/README.md
  pkg/models/services/README.md
Labels: documentation
